Vagrant.configure("2") do |config|
  config.vm.provider :docker do |d|
    d.image = "ubuntu:22.04"
    d.pull = true
    d.has_ssh = false
    d.remains_running = false
    d.cmd = ["sleep", "600"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -eux
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y qemu-system-x86-headless
    cd /vagrant
    chmod +x tests/run_qemu.sh
    QEMU_TIMEOUT_VALUE="${QEMU_TIMEOUT:-90}"
    QEMU_LOG_PATH=/vagrant/tests/vagrant/qemu.log
    QEMU_TIMEOUT="$QEMU_TIMEOUT_VALUE" QEMU_LOG="$QEMU_LOG_PATH" ./tests/run_qemu.sh DoomLinux.iso
  SHELL
end
